#!/usr/bin/python
# -*- coding: utf-8 -*-
 
import cgi
 
def htmlTop():
	print '''Content-type:text/html\n\n
    	<!DOCTYPE html>
    	<html>
        	<head>
            	<meta charset="utf-8">
            	<title> mAd LiBs </title>
        	</head>
        	<body>'''
 
def htmlTail():
	print '''</body>
    	</html>'''
 
 
def main():
	htmlTop()
	print '<h1>  Angry LIBs</h1>'
	print '''A gigantic contest in which you already may be a
      <form style = "display:inline;" action="NCS.py" method="get">
   	  <input type="text" 1="1" placeholder = "noun, singular" style = "display:inline;">
    .
    Anyone, and we mean anyone, can enter this
   	  <input type="text" 2="2" placeholder = "adj" style = "display:inline;">  
    contest.
    Just follow these
    <input type="text" 3="3" placeholder = "adj" style = "display:inline;">
    rules.
    Write down in
    <input type="text" 4="4" placeholder = "number" style = "display:inline;">
    words or less why you think
    <input type="text" 5="5" placeholder = "your mother's name" style = "display:inline;">
    	should be elected
    <input type="text" 6="6" placeholder = "noun" style = "display:inline;">
    	Of The Year. Remember she does not know that you think so
    <input type="text" 7="7" placeholder = "adverb" style = "display:inline;">
    	of her.
    	First prize will be a deluxe, three-speed
    <input type="text" 8="8" placeholder = "piece of technology" style = "display:inline;">
    	and a year’s supply of
    <input type="text" 9="9" placeholder = "noun" style = "display:inline;">
        .
Second prize will be a twenty one foot long
<input type="text" 10="10" placeholder = "noun" style = "display:inline;">
        .
 Third prize will be a full-color
<input type="text" 11="11" placeholder = "noun" style = "display:inline;">
 
 
 <input type="submit" value="Submit">
    </form> '''
 
 
 
	htmlTail()
 
main()
 
 
A gigantic contest in which you already may be a ___(noun,singular).
Anyone, and we mean anyone, can enter this ___(adjective) contest.
Just follow these ___(adjective) rules.
Write down in ___(number) words or less why you think ___(your Mother’s name) should be elected ___(noun) Of The
Year. Remember he/she does not know that you think so ___(adverb) of her.
First prize will be a deluxe, three-speed ___(piece of technology) and a year’s supply of ___(food item).
Second prize will be a twenty one foot long ___(noun). Third prize will be a full-color ___(noun)
plus a set of ___(animal,plural).
Each entry must be accompanied by a stamped, self-addressed ___(extraterrestrial being).
The decision will be final and in the event of a tie, duplicate ___(noun,plural) will be awarded.
 
