#!/usr/bin/python
# -*- coding: utf-8 -*-
 
import cgi
 
def htmlTop():
	print '''Content-type:text/html\n\n
    	<!DOCTYPE html>
    	<html>
        	<head>
            	<meta charset="utf-8">
            	<title> mAd LiBs </title>
        	</head>
        	<body>'''
 
def htmlTail():
	print '''</body>
    	</html>'''
 
 
def main():
	htmlTop()
	print '<h1>  Angry LIBs</h1>'
	print '''
        <form style = "display:inline;" action="NCS.py" method="get">
        <input type="text" name="1" placeholder = "adjective" style = "display:inline;">
            <br>
        <input type="text" name="2" placeholder = "adjective" style = "display:inline;">  
            <br>
        <input type="text" name="3" placeholder = "adj" style = "display:inline;">
            <br>
        <input type="text" name="4" placeholder = "name of a celebrity" style = "display:inline;">
            <br>
        <input type="text" name="5" placeholder = "name of another celebrity" style = "display:inline;">
            <br>
        <input type="text" name="6" placeholder = "animal" style = "display:inline;">
            <br>
        <input type="text" name="7" placeholder = "verb" style = "display:inline;">
            <br>
        <input type="text" name="8" placeholder = "noun" style = "display:inline;">
            <br>
        <input type="text" name="9" placeholder = "noun" style = "display:inline;">
            <br>
        <input type="text" name="10" placeholder = "body part" style = "display:inline;">
            <br>
        <input type="text" name="11" placeholder = "adverb" style = "display:inline;">
            <br>
        <input type="text" name="12" placeholder = "adjective" style = "display:inline;">
            <br>
        <input type="text" name="13" placeholder = "adverb" style = "display:inline;">
            <br> 
        <input type="text" name="14" placeholder = "adjective" style = "display:inline;">
            <br>
        <input type="text" name="15" placeholder = "noun plural" style = "display:inline;">
            <br>
        <input type="text" name="16" placeholder = "noun plural" style = "display:inline;">
            <br>
        <input type="text" name="17" placeholder = "noun plural" style = "display:inline;">
            <br>
	
 <input type="submit" value="Submit">
 	</form> '''
 
 
 
	htmlTail()
 
main()
